### ISSUE TITLE
KeyError: 'up_cross'

### ISSUE THREAD

**Issue by tanlingp** [WindVChen/DiffAttack#2]
Sorry to interrupt, code error Traceback (most recent call last).
  File "main.py", line 153, in <module>
    adv_image, clean_acc, adv_acc = run_diffusion_attack(tmp_image, label[ind:ind + 1].
  File "main.py", line 72, in run_diffusion_attack
    adv_image, clean_acc, adv_acc = diff_latent_attack.diffattack(diffusion_model, label, controller.
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/202221623173/DiffAttack-main/diff_latent_attack.py", line 369, in diffattack
    before_attention_map = aggregate_attention(prompt, controller, 7, ("up", "down"), True, 0, is_cpu=False)
  File "/202221623173/DiffAttack-main/utils.py", line 13, in aggregate_attention
    for item in attention_maps[f"{location}_{'cross' if is_cross else 'self'}"].
KeyError: 'up_cross'

**Comment by tanlingp** [comment]
Thank you very much for your help, it is indeed the reason for the wrong version

**Comment by kikyou-220** [comment]
Sorry to interrupt, I'm having this problem too, can I ask which version are you using?

**Comment by tanlingp** [comment]
The version given by the author

**Comment by nil0330** [comment]
> The version given by the author



> The version given by the author

I have the same question, and I'm unsure which specific version we need. Could you please assist me in clarifying this?

**Comment by WindVChen** [comment]
Hi @nil0330 ,

You can take a look at [requirements.txt](https://github.com/WindVChen/DiffAttack/blob/main/requirements.txt) for the versions of some packages.

Hope this helps.

**Comment by FiineLee** [comment]
Hi, @WindVChen 
I also have this problem, but I find my diffusers version is also 0.9.0.
