### ISSUE TITLE
运行出问题

### ISSUE THREAD

**Issue by zhangfeng0617** [WindVChen/DiffAttack#20]
您好，请问一下我已经把您发的预训练模型下载到了本地，更改了代码中的路径，还是出现这个问题呢，请问这是怎么回事？谢谢
![image](https://github.com/WindVChen/DiffAttack/assets/50318773/62477ef3-e198-46d9-b5a2-ea33d4ed243b)
![image](https://github.com/WindVChen/DiffAttack/assets/50318773/1e8d3c21-7987-4d8d-81fe-19e59c6bfa5a)

**Comment by WindVChen** [comment]
Hi @zhangfeng0617  ,

I didn't encounter such an issue before, but maybe you can have a look at this issue https://github.com/huggingface/transformers/issues/17611 which is quite similar.

Besides, there could also sometimes be internet problem. You can also have a try to add this script at the start of the code (refer to https://github.com/CompVis/stable-diffusion/issues/302#issuecomment-2042642642):
```python
import os
os.environ['HF_ENDPOINT']='https://hf-mirror.com'
```

If you want to load the pre-trained model from the local machine, you may need to ensure downloading the correct type of files. Below is the needed file list of Stable Diffusion:
![image](https://github.com/WindVChen/DiffAttack/assets/56162412/78f1d07f-a873-4b60-9c1f-35fe08400c1d)

**Comment by zhangfeng0617** [comment]
Thanks for your reply, can you give me a link to the pre-training model of this project? Maybe my pre-training model is not in the right file. thank you

**Comment by WindVChen** [comment]
Hi, you can find these files [here](https://huggingface.co/stabilityai/stable-diffusion-2-base/tree/main).

**Comment by zhangfeng0617** [comment]
thank you！ thank you！

**Comment by zhangfeng0617** [comment]
I downloaded the pre-training model to the local, there is this problem, hope you can help to answer it, thank you
![image](https://github.com/WindVChen/DiffAttack/assets/50318773/b47b0ac9-0d57-4417-a277-d4702b22685c)
******Attack based on Diffusion*********
Traceback (most recent call last):
  File "main.py", line 114, in <module>
    ldm_stable = StableDiffusionPipeline.from_pretrained(pretrained_diffusion_path).to('cuda:0')
  File "F:\Anaconda2023\anaconda3\envs\diffattack\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1037, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "F:\Anaconda2023\anaconda3\envs\diffattack\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 450, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "F:\Anaconda2023\anaconda3\envs\diffattack\lib\site-packages\transformers\tokenization_utils_base.py", line 2094, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'stabilityai/stable-diffusion-2-base\tokenizer'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'stabilityai/stable-diffusion-2-base\tokenizer' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

Process finished with exit code 1
![image](https://github.com/WindVChen/DiffAttack/assets/50318773/3e9c2866-7a88-414f-98f8-2f76b092f60e)

thanks！

**Comment by WindVChen** [comment]
Hi,

Could you please let me know the level of file path you passed into the code?

For example, here's my local save path:

![image](https://github.com/WindVChen/DiffAttack/assets/56162412/3d0dfa6d-6353-414e-8618-90b1ca8732e7)

And it should work when setting the `--pretrained_diffusion_path="C:\Users\PC\.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-base\snapshots\455a0f46082..."` in the main.py.

**Comment by zhangfeng0617** [comment]
This is the previous version you published, but it does not affect. I put the pre-trained model downloaded from the link you sent above into the project, and I also loaded it directly in the code. As shown in the figure. I see you put it under the C drive path, is that the reason? In addition, the pre-trained model I downloaded does not have huggingface\diffusers\ in front, is this affecting the operation? thank you
![image](https://github.com/WindVChen/DiffAttack/assets/50318773/820c0cc1-6633-44af-aa2d-4f04428fa21f)
![image](https://github.com/WindVChen/DiffAttack/assets/50318773/9cb8c1a0-5ce2-44a0-833d-a0a83e4c7395)

**Comment by WindVChen** [comment]
Ah, I think I understand the issue now.

I apologize for the confusion regarding the path specified in the code: `--pretrained_diffusion_path="stabilityai/stable-diffusion-2-base"`. The value `stabilityai/stable-diffusion-2-base` does not refer to a local path. Instead, it points to the Hugging Face repository `stabilityai/stable-diffusion-2-base` from which the necessary weights will be downloaded automatically.

The error message you encountered previously might be due to a name collision if you have a local directory with the same name as the Hugging Face repository. To resolve this, please try using an absolute path for the `--pretrained_diffusion_path` parameter. If that doesn't work, consider renaming your local folder to something else.

**Comment by zhangfeng0617** [comment]
It's okay. I'm the one who's learning and asking questions. I changed the local absolute path and changed the name of the pre-trained model, but it still didn't work. May I ask is there any other way? If I don't download the pre-trained model locally, I'll have a network problem like the one shown here. I really don't know what to do (crying and laughing), looking forward to your help, thank you.
![image](https://github.com/user-attachments/assets/55401768-4b82-420b-84b0-3fe5b82a00a1)

**Comment by WindVChen** [comment]
Emm, that's a bit weird.

Typically, setting --pretrained_diffusion_path="stabilityai/stable-diffusion-2-base" should automatically download the weights. The error message shown in the screenshot still seems to be related to a network connection issue. Have you tried the potential solutions mentioned [here](https://github.com/WindVChen/DiffAttack/issues/20#issuecomment-2213263016)?

**Comment by zhangfeng0617** [comment]
I tried the method but it didn't work. I will download your project again and try it. Thank you very much for your trouble.

**Comment by WindVChen** [comment]
Sorry it didn't work out :(  Please keep me informed if you manage to identify the issue.

**Comment by zhangfeng0617** [comment]
I re-downloaded your project, encountered this problem, I also set a property to true according to the online value, but it did not work。
![image](https://github.com/user-attachments/assets/29ddbbff-6bf1-4504-96b3-c054ea510133)
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

thank you！

**Comment by zhangfeng0617** [comment]
I re-downloaded your project to try, it is still the same problem, I will post all the information, please have a look, thank you！
Here is the error message:
F:\Anaconda2023\anaconda3\envs\diffattack\python.exe main.py --model_name inception --save_dir demo/output --images_root demo/images --label_path demo/labels.txt 
F:\Anaconda2023\anaconda3\envs\diffattack\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] 找不到指定的程序。'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(

******Attack based on Diffusion, Attacked Dataset: imagenet_compatible*********
urllib3.exceptions.SSLError: TLS/SSL connection has been closed (EOF) (_ssl.c:1135)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1135)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Anaconda2023\anaconda3\envs\diffattack\lib\site-packages\requests\adapters.py", line 589, in send
    resp = conn.urlopen(
  File "F:\Anaconda2023\anaconda3\envs\diffattack\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "F:\Anaconda2023\anaconda3\envs\diffattack\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/stabilityai/stable-diffusion-2-base (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1135)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 124, in <module>

**Comment by zhangfeng0617** [comment]
Hello, because I am busy with other things at this time, so I have delayed this. I re-downloaded your project and tried to replace the versions of the request and urllib3 libraries, but I still had this connection problem. Also, I downloaded stable-diffusion-2-base locally, but I didn't use it. I just downloaded the project, and then hooked up the vpn to run it directly, but the following problems kept appearing. Is there a problem with the process of my running the project? Could you help me, please? Thank you. It's so much trouble. If possible, it would be best to add your contact information, so that I can consult you more easily, because I do encounter this problem is rather difficult. It's perfectly normal for you to say no. Thank you again.


The following is the error message：

File "F:\Anaconda2023\anaconda3\envs\diffattack\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/stabilityai/stable-diffusion-2-base (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1135)')))"), '(Request ID: 38dcc369-6bd4-4e11-988c-2d545872bbb3)')

**Comment by WindVChen** [comment]
Hi @zhangfeng0617 ,

Apologies for the delayed response—things have been quite busy on my end as well.

Please feel free to send an email to [windvchen@gmail.com](mailto:windvchen@gmail.com), and I'll share my personal contact details there.

**Comment by zhangfeng0617** [comment]
Ok, thank you, now I am busy with some other things, I will contact you when the school starts, thank you very much

**Comment by zhangfeng0617** [comment]
Ok, thank you, now I am busy with some other things, I will contact you when the school starts, thank you very much

**Comment by zhangfeng0617** [comment]
I found the reason for this SSL error, because I hung up the vpn, the browser can access huggingface, but Pycharm can not access, I tried to use python to access Google, also failed to access, reported this SSL6 error. So do you have any good way to solve this problem, or download the file to the local by myself? I am not clear about the steps and configuration methods, I hope you can help me, thank you for your trouble

**Comment by zhangfeng0617** [comment]
The previous problem has been solved, because the hanging vpn only proxy browser, no proxy Pycharm. Now this problem has arisen, may I ask what the problem is, thank you very much

![Uploading image.png…]()

**Comment by zhangfeng0617** [comment]
The previous problem has been solved, because the hanging vpn only proxy browser, no proxy Pycharm. Now this problem has arisen, may I ask what the problem is, thank you very much

******Attack based on Diffusion, Attacked Dataset: imagenet_compatible*********
vae\diffusion_pytorch_model.safetensors not found
Fetching 13 files:   0%|          | 0/13 [00:00<?, ?it/s]

**Comment by WindVChen** [comment]
Hi,

From the error message, you may need to check if you've downloaded `diffusion_pytorch_model.safetensors` under the folder `vae`.
