### ISSUE TITLE
huggingface download error

### ISSUE THREAD

**Issue by junyizeng** [WindVChen/DiffAttack#5]
Thank you very much for your open source, I have encountered the following problem with the pre-trained diffusion model from huggingface.

Traceback (most recent call last):
  File "/root/code/DiffAttack-main/main.py", line 107, in <module>
    ldm_stable = StableDiffusionPipeline.from_pretrained(pretrained_diffusion_path).to('cuda:0')
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 884, in from_pretrained
    cached_folder = cls.download(
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1208, in download
    config_file = hf_hub_download(
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1259, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

**Comment by WindVChen** [comment]
Hi @junyizeng ,

It seems that there is a problem with the Internet connection. Maybe you can check some possible solutions [here](https://github.com/huggingface/transformers/issues/10067).

**Comment by junyizeng** [comment]
Thank you very much for your quick reply. Due to the limitation of the device, I am renting the online calculator platform (AutoDL) to run the code, but the file downloaded by stable_diffusion is too large and the system disk is easily filled up, which affects the normal operation of the code. Can I download the files needed to load stable_diffuion in advance and import the model from local? Since this is my first time to use huggingface, could you please provide a tutorial if possible?

**Comment by WindVChen** [comment]
Since I'm unfamiliar with AutoDL platform, I'm unsure whether the way I run it with local files will bring some inspiration.

You can first download the files by directly running the following codes on the local machine:

```
from diffusers import StableDiffusionPipeline
ldm_stable = StableDiffusionPipeline.from_pretrained(“stabilityai/stable-diffusion-2-base”)
```

Then, you can find these files in the local path (take Win10 as an example): `C:\Users\$YourName$\.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-base\snapshots\$A Long Serial Number$`.

After that, you can directly load the local files without again downloading from the Internet:
```
from diffusers import StableDiffusionPipeline
ldm_stable = StableDiffusionPipeline.from_pretrained("C:\Users\$YourName$\.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-base\snapshots\$A Long Serial Number$")
```

**Comment by junyizeng** [comment]
Thank you very much, the method you gave is effective!

**Comment by yuuma002** [comment]
Hi. Thanks for open-sourcing the code of your wonderful work. I met the same error and I cannot fix the error by https://github.com/huggingface/transformers/issues/10067. Could you provide the detailed fixing method of the issue @WindVChen? 

> Hi @junyizeng ,
> 
> It seems that there is a problem with the Internet connection. Maybe you can check some possible solutions [here](https://github.com/huggingface/transformers/issues/10067).

**Comment by WindVChen** [comment]
Hi @yuuma002 ,

Thanks for your attention. If still fail to download the weight automatically, maybe you can try to download it manually. Try to download all the files [here](https://huggingface.co/stabilityai/stable-diffusion-2-base/tree/main) (no need to download `512-base-ema.ckpt` and `512-base-ema.safetensors`) and save them into a directory (let us name it as A), then you can try to load the weight by:
``` python
from diffusers import StableDiffusionPipeline
ldm_stable = StableDiffusionPipeline.from_pretrained(A)
```

Hope this can help.

**Comment by zhangfeng0617** [comment]
> 由于我对 AutoDL 平台不熟悉，我不确定使用本地文件运行它的方式是否会带来一些灵感。
> 
> 您可以先在本地直接运行以下代码来下载文件：
> 
> ```
> from diffusers import StableDiffusionPipeline
> ldm_stable = StableDiffusionPipeline.from_pretrained(“stabilityai/stable-diffusion-2-base”)
> ```
> 
> 然后，您可以在本地路径中找到这些文件（以 Win10 为例）：。`C:\Users\$YourName$\.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-base\snapshots\$A Long Serial Number$`
> 
> 之后，您可以直接加载本地文件，而无需再次从 Internet 下载：
> 
> ```
> from diffusers import StableDiffusionPipeline
> ldm_stable = StableDiffusionPipeline.from_pretrained("C:\Users\$YourName$\.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-base\snapshots\$A Long Serial Number$")
> ```

Hello, when I load the local model like this, there are two errors. One is HFValidationError and the other is OSError, which says I cannot connect to https://huggingface.co but I want to load the local model. I put local_files_only = True, but this error will still be reported. Hope for your help, thank you
